### ISSUE TITLE
Parallel computation box greyed out in 1.0.6

### ISSUE THREAD

**Issue by bobmyhill** [ComputationalThermodynamics/MAGEMin#14]
A couple of plausibly related issues after installing 1.0.6 on a MacBook Pro (M1). Combined here for brevity.

1) The box allowing specification of the path to mpiexec is greyed out:
<img width="291" alt="image" src="https://user-images.githubusercontent.com/8144905/159303302-482f0fdb-505f-4ab4-a582-103f37ec33da.png">

2) Turning off parallel computations allows calculations to run, but every calculation is accompanied by a warning that starts
''Do you want the application “MAGEMin” to accept incoming network connections?''

My machine is behind a firewall (university rules, alas), so I can't accept incoming connections, and I can't turn these messages off (Accept and Deny don't appear to do anything to later calculations). 

Any suggestions much appreciated.

**Comment by NicolasRiel** [comment]
I am not sure about what is happening with the MPI call through Julia here. 
But concerning the manual installation of MAGEMin, it should not be too hard, at least it is quite straigthforward on Linux. I don't have much experience with Mac, but the more or less tricky part 1 year ago was to get the C version of ``lapack`` installed: ``lapacke``. I know that Boris could get ``lapacke`` by simply manually installing it from the ``lapack`` library available on netlib (http://www.netlib.org/lapack/). Moreover, from what I could read ``lapacke`` is now included in the default ``lapack`` package available with Brew. So hopefully you can get all the needed libraries only using Brew (namely mpich, NLopt and lapacke). Then you need to link the libraries path correctly. For this an example for a Mac system is given in the ``Makefile``.
If you have any problem please come back to us.

**Comment by boriskaus** [comment]
Thanks for the explanation; We really appreciate your help in checking this and we would certainly like the matlab/Julia based based version to work, as users are likely to prefer that. Unfortunately, I don't have access to a M1 system which makes debugging a bit tricky.

So the `mpiexec` based code seems to fail for you, but the point-wise calculations work. This suggests that there could be a problem with the way `mpiexec` & friends are compiled for the apple M1 architecture. You can try to run this directly from the `julia` console (making sure that you are in the same directory as `MAGEMin_input.dat`).

We had some discussions about how to combine/call `mpi` with `MAGEMin` this last week, which you can read [here](https://github.com/JuliaPackaging/Yggdrasil/pull/4624).

Could you do a few tests, to check this?

1. First load `MAGEMin_jll`, which should be available on your system
```julia
julia> using MAGEMin_jll
```
2. Next, can you run the point wise calculations on a single CPU?
```julia
julia> run(`$(MAGEMin()) --Verb=0 --File=MAGEMin_input.dat --n_points=650 --test=0`);
```
I suspect that the Mac firewall message will pop up at this stage (I can look into that later). I expect that this should still work.

3.  Next we can try to follow last weeks suggestion:
```Julia
julia> const mpirun = if MAGEMin_jll.MPICH_jll.is_available()
    MAGEMin_jll.MPICH_jll.mpiexec()
elseif MAGEMin_jll.MicrosoftMPI_jll.is_available()
    MAGEMin_jll.MicrosoftMPI_jll.mpiexec()
else
    nothing
end
```
after which running this in parallel *should ideally* be possible with:
```Julia
julia> run(`$(mpirun) -n 2  $(MAGEMin()) --Verb=0 --File=MAGEMin_input.dat --n_points=650 --test=0`);
```

Let us know at which step it errors. From MATLAB, we don't do anything else as load the path to the required dynamic libraries and make a system call to that, so if it works from within Julia it will be possible to get this working from matlab as well.

**Comment by boriskaus** [comment]
To get back to this issue:
> 2\. I set the binary to safe in the firewall settings (which is where the warning told me to go) before raising this issue, but there's no change in behaviour after doing that. I'll chalk it up to Mac weirdness.

I was able to reproduce this on an intel Mac, and could push a fix for it. It essentially blocks incoming traffic for the `MAGEMin` binary. The fix is in the file [/julia/firewall_macos.jl](https://github.com/ComputationalThermodynamics/MAGEMin/blob/main/julia/firewall_macos.jl), which you can run from the terminal with
```
$julia firewall_macos.jl
```
Note that you do need to have the `sudo` password for your machine. If that is not the case, you will have you ask your system administrator for help. 

You will need to run this once for every version of `MAGEMin` (if you update at some stage in the future, this will likely have to be repeated).

**Comment by bobmyhill** [comment]
Hi @boriskaus 

Thanks for looking into this for me. I independently did the same thing as you (in between lectures and practicals) and got similar results both for a single core and multiple cores. The only difference is that I use openmpi, so the includes were a bit different:

```
LIBS    = -lm -framework Accelerate /opt/homebrew/opt/lapack/lib/liblapacke.dylib /opt/homebrew/opt/nlopt/lib/libnlopt.dylib /opt/homebrew/opt/openmpi/lib/libmpi.dylib  
INC     = -I/opt/homebrew/opt/openmpi/include/ -I/opt/homebrew/opt/lapack/include -I/usr/local/include -I/opt/homebrew/opt/nlopt/include/
```

MATLAB remained unhappy until I removed the version of MAGEMin in julia, and also removed an old matlab.mat file from the root directory. Everything now appears to work, both from the command line and from MATLAB :) 

I shall now play around which what looks like a very impressive solution to an age-old problem! Thanks for your help.

**Comment by boriskaus** [comment]
> MATLAB remained unhappy until I removed the version of MAGEMin in julia

Hmm, if both the Julia version and a locally compiled version are present, the button should be active with which you can switch between the two versions. The Julia version is the default one in that case.

**Comment by NicolasRiel** [comment]
Thank you for letting us know the LIBS and INC that you used with openmpi.
I am adding this to the documentation.
