### ISSUE TITLE
isentropic melting paths

### ISSUE THREAD

**Issue by NicolasRiel** [ComputationalThermodynamics/MAGEMin#34]
Incorporating computation of isentropic melting paths to MAGEMin would allow for a range of useful mantle melting studies.

*[request from Brendan Dyck]*

**Comment by boriskaus** [comment]
Is this not something that is best done through the Julia interface?

**Comment by NicolasRiel** [comment]
Actually yes, this should be done as post-processing on the user part. I will do it as an exercise to provide a Julia example.
