### ISSUE TITLE
A beginner's problem

### ISSUE THREAD

**Issue by CHNxzr** [ComputationalThermodynamics/MAGEMin#40]
When I change the composition for my own samples, the computation always be terrible. Could anyone helps me?
![mistake](https://user-images.githubusercontent.com/114136385/191682071-a9f3712e-a07f-4e9a-a6ed-81b144422958.png)

**Comment by boriskaus** [comment]
Thanks for your interest in using MAGEMin! I need a bit more information to try and reproduce the problem you are experiencing:

1.  Which version of MAGEMin are you using. 
2. Which operating system do you have (linux, max, windows)? Version of the operating system would also be handy to have
3. Can you explain the steps you did to arrive at the error message above. Perhaps upload a screenshot of the GUI so we can see the options you used. 
4. It would also be great to see the full output of the MATLAB Command Window (also what happened before the error message)

**Comment by CHNxzr** [comment]
Thanks for reply! Here are two screenshots. I use windows 11 system and have updated for newest version.The composition is just set randomly here. 
![reply1](https://user-images.githubusercontent.com/114136385/191692753-7bba10b7-27c7-4539-b079-3ff4c5ee9a0f.png)
![reply2](https://user-images.githubusercontent.com/114136385/191692772-398219c0-9c8f-40d2-8321-07af4671df04.png)

**Comment by boriskaus** [comment]
that is curious, as the newest version of MAGEMin is version 1.2.7 (which was pushed around an hour ago) and not 1.2.3 as you seem to be using. The previous release was 1.2.4. So it might be that you were using the 1.2.3 GUI with the 1.2.4 binary, which won't work.

Can you try downloading the latest version of MAGEMin, e.g. [here](https://github.com/ComputationalThermodynamics/MAGEMin/releases) in a fresh directory? Also, please run the installer again and check which version of MAGEMin you are using.

**Comment by CHNxzr** [comment]
It is a pity that the same situation still occurs when the latest version(1.2.7) is updated. I have  deleted  old version. Here are some screenshots,  are there some problems with the installation?
![reply3](https://user-images.githubusercontent.com/114136385/191717510-c1016635-5354-4d16-9de4-4f4a30a1dc5a.png)
![reply4](https://user-images.githubusercontent.com/114136385/191717519-5c73ce86-320b-4800-b51a-ab7640341c47.png)
![reply5](https://user-images.githubusercontent.com/114136385/191717521-661ae68d-de48-490e-aade-513c98993c32.png)
![reply6](https://user-images.githubusercontent.com/114136385/191717526-2213a800-cfcc-4dd2-b125-cdf5e2b0cc59.png)

**Comment by NicolasRiel** [comment]
Hi, could it be that the last entry of the input composition is an integer? Could you try 0.0 instead?

**Comment by boriskaus** [comment]
I managed to reproduce your problem. You should click the button that says "Parallel computations" and it will likely work fine for you. I was able to run the diagram for your composition.

**Comment by CHNxzr** [comment]
In addition, I found this during the installation(1.2.7)， but the path is not wrong.
![reply11](https://user-images.githubusercontent.com/114136385/191731425-fc59cbc6-7891-4c87-b6b0-0901bf7ec53c.png)

**Comment by boriskaus** [comment]
yes, this last statement is to be expected. The reason is that we only updated MAGEMin to version 1.2.7 today, and it always takes a day or so for the binary version to be updated to the same version.

I am still a little bit puzzled, as this works fine for me, also for your composition. Yet, I am using a Mac and not a windows machine (Nico will try later with his windows machine). 
It almost seems to me that MAGEMin is not running at all for you and therefore does not generate output. Yet, at the end of the installation script you should have been able to do an example calculation. Did that work fine?

And what is the content of the "environmental_variables.m" file?

**Comment by CHNxzr** [comment]
Yes, exactly when I use the predefined composition and not change the P,T setting , just click"start new computation" , there is no wrong.
And here is a sreenshot for  "environmental_variables.m".
![reply12](https://user-images.githubusercontent.com/114136385/191734050-c1b00b5d-9828-4dd9-a9aa-609207d841dd.png)

**Comment by boriskaus** [comment]
Can you try to run the following lines in your MATLAB console?
```matlab
>> Computation.BinaryMethod = 'Default';
>> exe = MAGEMin_exe(Computation)
>> P=10; T=1000;
>>  command = [exe, ' --Pres=',num2str(P),' --Temp=',num2str(T),' --test=0'];
>>  environmental_variables;
>>  Computation.path_bin = path_bin;
>>  Computation.path_dylib = path_dylib;
>>  command = add_dynamic_libs(command, Computation);
>>  system(command);

Running MAGEMin 1.2.4 [02/09/2022] on 1 cores {
═══════════════════════════════════════════════
 Status             :            0 
 Mass residual      : +5.04456e-06
 Rank               :            0 
 Point              :            0 
 Temperature        :  +1000.00000	 [C] 
 Pressure           :    +10.00000	 [kbar]

 SOL = [G: -816.684] (33 iterations, 679.47 ms)
 GAM = [-1001.704437,-1811.505257,-811.971422,-688.708292,-400.822840,-956.411928,-861.932627,-1057.384402,-270.340930,-1357.576491]

 Phase :      opx      spn      cpx       ol 
 Mode  :  0.23700  0.01830  0.14694  0.59776 
___________________________________
MAGEMin comp time: +779.126000 ms }
```

**Comment by CHNxzr** [comment]
Change P,T settings is still fine, however the Chinese error messages still exist.
Ok, I'll try.
![reply13](https://user-images.githubusercontent.com/114136385/191736060-47a6e711-ae36-4323-b5fc-41829ceb5c14.png)

**Comment by boriskaus** [comment]
so this is correct, which shows that `MAGEMin.exe` has been downloaded to your system and can be executed. 

Yet, if you start calculations through the main GUI, it seems to be unable to find `MAGEMin.exe`

**Comment by CHNxzr** [comment]
![reply14](https://user-images.githubusercontent.com/114136385/191737813-a57317c2-2480-43b5-8b61-3bd6fb9704c8.png)
Just as you say!

**Comment by boriskaus** [comment]
no, you made mistake above. It should be `Computation.path_dylib` (underscore) and not `Computation.path.dylib` (dot). Try correcting that.

**Comment by CHNxzr** [comment]
![reply15](https://user-images.githubusercontent.com/114136385/191739033-8b523339-5326-4d45-b91d-10893b543b01.png)

**Comment by boriskaus** [comment]
ha that is interesting and seems to suggest that `path_bin` and `path_dylib` are actually empty. 
Can you show the content of the following variables?
```
>> command
>> path_dylib
>> path_bin
```

**Comment by CHNxzr** [comment]
Exactly there is no  space between MAGEMin.exe and --Pres
Screenshots show the content of path_bin, the other two are more complicated.
![Uploading reply16.png…]()

**Comment by CHNxzr** [comment]
![reply17](https://user-images.githubusercontent.com/114136385/191741958-4f586126-f4b3-4067-b671-508bf1aa89c5.png)
![reply18](https://user-images.githubusercontent.com/114136385/191741960-9e445fe8-4c32-4723-be6d-1918d8df4829.png)

**Comment by CHNxzr** [comment]
![reply16](https://user-images.githubusercontent.com/114136385/191742219-54e77b39-5d1b-412f-b02c-b491e7583e22.png)

**Comment by boriskaus** [comment]
well there has to be spaces between `MAGEMin.exe` and ` --Pres`. Same with `--Temp` and `--test`, as it can otherwise not work. Can you fix that carefully and try again?

**Comment by CHNxzr** [comment]
wow!
![reply19](https://user-images.githubusercontent.com/114136385/191749808-03fac175-373a-4f33-b4f4-3658e4c48e13.png)

**Comment by boriskaus** [comment]
yes this was to be expected as I execute the exact same lines of code at the end of the installation script (which was already working for you).

Meanwhile:
1. Nico fixed the bug that prevented non-parallel cases to work
2. The automatically downloaded MAGEMin binary version was updated to 1.2.7

We still need to find out why you are unable to run MAGEMin from the GUI. Given the changes, can you
- download a fresh version of MAGEMin (from the main page by going to code-> download ZIP
- restart matlab before running this again
- rerun the installer script again; this should download version 1.2.7

thanks!

**Comment by CHNxzr** [comment]
I have updated it as instructed. Now the binary version is 1.2.7. 
![reply20](https://user-images.githubusercontent.com/114136385/191756464-5605e04d-9871-4998-b351-748f8059e1d5.png)
![reply21](https://user-images.githubusercontent.com/114136385/191756480-9982fb7d-59dd-40a2-af1e-570467373a3d.png)

**Comment by boriskaus** [comment]
and what happens is you unclick the "Parallel computations"?

**Comment by CHNxzr** [comment]
It seems to be a similar problem.
![reply22](https://user-images.githubusercontent.com/114136385/191757185-cc9fc490-5006-4e6c-8215-97b3bf5c27fc.png)

**Comment by NicolasRiel** [comment]
Could it be that you don't have all the privileges on your machine? Could you try to run matlab as administrator?

**Comment by CHNxzr** [comment]
![reply23](https://user-images.githubusercontent.com/114136385/191762475-670cc2ec-6954-429b-950c-b143167594ba.png)
![reply24](https://user-images.githubusercontent.com/114136385/191762489-b836bc1a-3a56-49d3-bb82-c83fec186e8f.png)
How long does it take to caculate 42 points?  Ten minutes later, It seems to be the same.

**Comment by boriskaus** [comment]
yes it seems to be unable to find `MAGEMin.exe` on your system & hangs (so it did not actually do a calculation). 42 points should only take a few seconds.
On our side we are unable to reproduce this, even on our windows machine. 
In order to help us with debugging, I created a modified version of `Execute_MAGEMin.m`, attached here (in zip format).
Can you please put that in the `/matlab` directory of MAGEMin, replacing the file that is there? 
It will give me some more info about what your system does.

 
[Execute_MAGEMin.m.zip](https://github.com/ComputationalThermodynamics/MAGEMin/files/9626358/Execute_MAGEMin.m.zip)

**Comment by CHNxzr** [comment]
![reply26](https://user-images.githubusercontent.com/114136385/191766913-bf72d3da-018d-456c-82dd-ca2eeab17204.png)

**Comment by NicolasRiel** [comment]
Thanks for reporting the last problem. I can also reproduce it. After checking, it appears that O2 is stabilized (with your bulk). It seems that your system if over-oxidized, if you reduce the wt% of O to value more reallistic ones such as 0.5, it works.
I will do some more testing to see if I need to deactivate O2 as a pure species and if I can solve your problem when O2 pure species if off.
Nico

**Comment by CHNxzr** [comment]
![reply27](https://user-images.githubusercontent.com/114136385/191769387-9292b3d2-eaa1-45f8-95a2-0efa23c4739e.png)
Like this? it seems nothing happened.

**Comment by boriskaus** [comment]
you should copy and paste the line that you see in the command window that starts with `' set PATH=C:\ ..'` which is too long for me to see, and insert that instead of `'Copy paste ...'`
thanks!

**Comment by CHNxzr** [comment]
> Thanks for reporting the last problem. I can also reproduce it. After checking, it appears that O2 is stabilized (with your bulk). It seems that your system if over-oxidized, if you reduce the wt% of O to value more reallistic ones such as 0.5, it works.
> I will do some more testing to see if I need to deactivate O2 as a pure species and if I can solve your problem when O2 pure species is deactivated.
> Nico

wow! It works.
![reply28](https://user-images.githubusercontent.com/114136385/191771007-98e10405-1592-4395-9cc7-df5f3c65dae5.png)

**Comment by CHNxzr** [comment]
Instead, it seems to be slow 
![reply29](https://user-images.githubusercontent.com/114136385/191774284-05ef4466-046e-455d-8932-351aa1fbcac0.png)
.

**Comment by boriskaus** [comment]
depends a bit on your system & whether you are using a multicore processor or not.

**Comment by CHNxzr** [comment]
but it's not bad for a me! Thanks to both of you very much.

**Comment by boriskaus** [comment]
you're welcome!
