### ISSUE TITLE
Can this software be installed on window systems?

### ISSUE THREAD

**Issue by NicolasRiel** [ComputationalThermodynamics/MAGEMin#46]
Can this software be installed on window systems?

_Originally posted by @sunguochao in https://github.com/ComputationalThermodynamics/MAGEMin/issues/45#issuecomment-1260489052_

**Comment by boriskaus** [comment]
ofcourse

**Comment by NicolasRiel** [comment]
Yes, you need to download the archive, and launch Matlab 2019+

Details are given on the main repo:

https://github.com/ComputationalThermodynamics/MAGEMin
