### ISSUE TITLE
Parallel computation slow on apple silicon mac

### ISSUE THREAD

**Issue by eazzzon** [ComputationalThermodynamics/MAGEMin#50]
Hi

I am trying to run the parallel computation with the matlab interface but runs very slow, actually one core model runs even faster.

I followed this [issue](https://github.com/ComputationalThermodynamics/MAGEMin/issues/14), and have complied with homebrew for `NLopt`, `MPICH` and `LAPACK`, then makefile but got an error below:

<img width="645" alt="image" src="https://user-images.githubusercontent.com/34231327/220456166-00af7ea2-06fe-4ecf-889a-7efb3123f0cc.png">

Not very familiar with makefiles, any idea of how to make this work? This might be a beginner's issue..Thanks in advance!

**Comment by boriskaus** [comment]
Yes, I also noticed a few days ago that it is indeed running slow on the newer apple silicon systems, if using the Julia BinaryBuilder version. It runs very fast if you compile it manually/locally, which suggests that there is a problem with the BB version. I'll see if I can find what the issue is (may take a bit, depending on my time).

### Local compilation
On a a mac, the easiest way to install the required binaries `nlopt` and `mpich` is to compile them through [homebrew](https://brew.sh). First install homebrew, followed by:
```
$ brew install nlopt
$ brew install mpich
$ bre install lapack
```
Next, you will have to adapt the makefile. We just updated that to link to the default hombrew directories, but from what you show above it seems you are using an older version. Have a look at the latest version [here](https://github.com/ComputationalThermodynamics/MAGEMin/blob/main/Makefile). The makefile is a textfile, so you can comment the lines you don't need and try this again.

**Comment by eazzzon** [comment]
Hi,

Thanks, the new makefile works. 
<img width="351" alt="image" src="https://user-images.githubusercontent.com/34231327/220570049-dfa6fc37-5eb5-4ea4-adcd-69d99ad9ff2c.png">

But matlab interface seems only work on refinement level 1 (very fast calculation speed) then stops with error. Any idea how to fix the mpiexec path not found error?
<img width="673" alt="image" src="https://user-images.githubusercontent.com/34231327/220571572-bfd08e2a-6503-43a1-b11d-fe6fff84ddd3.png">

PS: I think I am running with the local executable as shown here. The default version is still super slow (which I believe is what you mentioned in this [issue](https://github.com/ComputationalThermodynamics/MAGEMin/issues/14)
<img width="387" alt="image" src="https://user-images.githubusercontent.com/34231327/220572456-fd61b863-4fd7-4588-b4d6-10f2ed448b1e.png">

**Comment by NicolasRiel** [comment]
Hi,

Here the problem is that the calculation is not performed because the path to mpiexec is likely wrong.
As you can see on your screenshot: "/user/bin//mpiexec"
Try to change the path to /usr/bin and not /usr/bin/

Hope this helps!

**Comment by boriskaus** [comment]
I leave it open until we resolve the issue with the BinaryBuilder version of MAGEMin being slow

**Comment by eazzzon** [comment]
A bit feedback, I am curious if the default binarybuilder being slow is because of julia? I did a loop with julia interface and it turns out takes 0.5 - 1s for one point and occasionally 2s. Could also because I didn't probably loop it wisely...

**Comment by boriskaus** [comment]
no, I think it has to do with how the binaries are compiled.

**Comment by eazzzon** [comment]
Hi

the new updated 1.3.0 seems has this issue back. but different error:
```
MAGEMin   1.3.0 [06/03/2023]

zsh:1: no matches found: _pseudosection_output.*.*
/opt/homebrew/bin/mpiexec -n 6 ./MAGEMin --out_matlab=0 --solver=1 --Verb=0 --sys_in=mol --db=ig --File=MAGEMin_input.dat --n_points=49 --test=0

command =

    'export PATH=/Users/easonzz/.julia/artifacts/abb7cbd1c6369f566bf0334f8e033f35b639d0e6/bin:/Users/easonzz/.julia/artifacts/5ead90ea92128f3bba70df07a389c372594e09db/bin ;  export DYLD_LIBRARY_PATH=/Users/easonzz/.julia/artifacts/900c5f3ba53bb0d128142a78da39027c65597b0f/lib:/Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia:/Users/easonzz/.julia/artifacts/bf797a6e6d1fcc01635d6b2723ac0390c82f41d2/lib:/Users/easonzz/.julia/artifacts/abb7cbd1c6369f566bf0334f8e033f35b639d0e6/lib:/Users/easonzz/.julia/artifacts/5ead90ea92128f3bba70df07a389c372594e09db/lib:/Applications/Julia-1.8.app/Contents/Resources/julia/bin/../lib/julia:/Applications/Julia-1.8.app/Contents/Resources/julia/bin/../lib; /opt/homebrew/bin/mpiexec -n 6 ./MAGEMin --out_matlab=0 --solver=1 --Verb=0 --sys_in=mol --db=ig --File=MAGEMin_input.dat --n_points=49 --test=0'

No matching processes belonging to you were found

ans =

     1

--------------------------------------------------------------------------
The value of the MCA parameter "plm_rsh_agent" was set to a path
that could not be found:

  plm_rsh_agent: ssh : rsh

Please either unset the parameter, or check that the path is correct
--------------------------------------------------------------------------
[MBAEZ.local:90369] [[INVALID],INVALID] FORCE-TERMINATE AT Not found:-13 - error plm_rsh_component.c(335)
export PATH=/Users/easonzz/.julia/artifacts/abb7cbd1c6369f566bf0334f8e033f35b639d0e6/bin:/Users/easonzz/.julia/artifacts/5ead90ea92128f3bba70df07a389c372594e09db/bin ;  export DYLD_LIBRARY_PATH=/Users/easonzz/.julia/artifacts/900c5f3ba53bb0d128142a78da39027c65597b0f/lib:/Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia:/Users/easonzz/.julia/artifacts/bf797a6e6d1fcc01635d6b2723ac0390c82f41d2/lib:/Users/easonzz/.julia/artifacts/abb7cbd1c6369f566bf0334f8e033f35b639d0e6/lib:/Users/easonzz/.julia/artifacts/5ead90ea92128f3bba70df07a389c372594e09db/lib:/Applications/Julia-1.8.app/Contents/Resources/julia/bin/../lib/julia:/Applications/Julia-1.8.app/Contents/Resources/julia/bin/../lib; /opt/homebrew/bin/mpiexec -n 6 ./MAGEMin --out_matlab=0 --solver=1 --Verb=0 --sys_in=mol --db=ig --File=MAGEMin_input.dat --n_points=49 --test=0: Signal 115

ForwardSimulation_Time =

    0.2515

Error using sscanf
First argument must be a text scalar.

Error in ReadPseudoSectionData_MAGEMin (line 34)
    A       = sscanf(line,'%f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f');

Error in PerformMAGEMin_Simulation (line 100)
            [PhaseData, Status] = ReadPseudoSectionData_MAGEMin(newPoints, PhaseData,
            Computation.MinPhaseFraction);

Error in ComputePhaseDiagrams_AMR (line 123)
    [PhaseData, TP_vec, FailedSimulations, CancelComputation] =
    PerformMAGEMin_Simulation(PhaseData, newPoints, TP_vec, VerboseLevel, Chemistry, dlg,
    ComputeAllPoints, UseGammaEstimation, Computation);

Error in PlotPseudosection/StartNewComputation (line 1533)
            [PseudoSectionData, CancelComputation]       =
            ComputePhaseDiagrams_AMR(PseudoSectionData, DisplayPlots);
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 386)
Error while evaluating Button PrivateButtonPushedFcn.
```
The new self-complied 1.3.0 works
<img width="330" alt="image" src="https://user-images.githubusercontent.com/34231327/227249156-a0fe53b0-0a48-46f4-8668-380fff6fdaaf.png">
Below is my GUI settings for local paraller calculation:
![image](https://user-images.githubusercontent.com/34231327/227249486-6f76d4f1-5a2e-43b1-a5b2-78ad0cf9fd19.png)

default path `/usr/bin` also didn't work

Any idea what might cause the issue?

**Comment by NicolasRiel** [comment]
It seems to me that it is trying to run with the binary builder version while you are giving a local path for mpi.
How did you install the last version?

Did you compile MAGEMin yourself? Or did you install it with the binary builder?

**Comment by eazzzon** [comment]
Hi,

Both previous version (1.2.8) and 1.3.0 I installed with the MATLAB GUI, yes there is an environmental variable `.m` file created after the installation. I then complied MAGEMin myself to enable a local paraller model. it worked with 1.2.8 but doesn't work with 1.3.0. 

here are what in my environmental variable file if that is useful?

```
path_dylib = '/Users/easonzz/.julia/artifacts/900c5f3ba53bb0d128142a78da39027c65597b0f/lib:/Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia:/Users/easonzz/.julia/artifacts/bf797a6e6d1fcc01635d6b2723ac0390c82f41d2/lib:/Users/easonzz/.julia/artifacts/abb7cbd1c6369f566bf0334f8e033f35b639d0e6/lib:/Users/easonzz/.julia/artifacts/5ead90ea92128f3bba70df07a389c372594e09db/lib:/Applications/Julia-1.8.app/Contents/Resources/julia/bin/../lib/julia:/Applications/Julia-1.8.app/Contents/Resources/julia/bin/../lib'; 
path_bin = '/Users/easonzz/.julia/artifacts/abb7cbd1c6369f566bf0334f8e033f35b639d0e6/bin:/Users/easonzz/.julia/artifacts/5ead90ea92128f3bba70df07a389c372594e09db/bin'; 
path_julia = '/Applications/Julia-1.8.app/Contents/Resources/julia/bin'; ```

**Comment by NicolasRiel** [comment]
What happens if you try to run that command in the MAGEMin directory (make sure that the MAGEMin_input.dat exists, if not try first to run the GUI until it crashes):

/opt/homebrew/bin/mpiexec -n 6 ./MAGEMin --out_matlab=0 --solver=1 --Verb=0 --sys_in=mol --db=ig --File=MAGEMin_input.dat --n_points=49 --test=0

**Comment by eazzzon** [comment]
Hi, it works well in this way with output.

<img width="792" alt="image" src="https://user-images.githubusercontent.com/34231327/227538306-521f203d-5987-4ac5-9c56-08e89e4d2be2.png">

Looks like this is a miscommunicate with MATLAB GUI and the mpi?

On a related note, is there a way to save the results from the terminal like this? I guess I would need the GUI to generate a dat file first?

**Comment by NicolasRiel** [comment]
So the problem is that the GUI is loading the environment variables. Try to delete the .m file then, and the GUI should work without problems with the local MPI.

**Comment by eazzzon** [comment]
amazing, fixed!

> So the problem is that the GUI is loading the environment variables. Try to delete the .m file then, and the GUI should work without problems with the local MPI.

**Comment by eazzzon** [comment]
thank you Boris, it works great now
