### ISSUE TITLE
Can our software draw T-H2O or P-H2O diagramm?

### ISSUE THREAD

**Issue by CHNxzr** [ComputationalThermodynamics/MAGEMin#52]
Dr. Tobias Keller:
         I'm very happy to see that the new database is installed, so another problem is  should I uninstall the old version? 
         May your team achieve greater success in future!

                                                                                                David xue
                                                                                   A graduate student in China

**Comment by NicolasRiel** [comment]
Quick update.
The framework for P-X and T-X diagrams is not working in the C code. I am working on adding these options to the GUI.

Cheers

**Comment by NicolasRiel** [comment]
The PlotPseudosection.mlapp has been updated to compute TX and PX diagrams. You can now compute diagrams with any desired range of composition with fixed pressure or temperature.
If you find any bug please report them!
