### ISSUE TITLE
calculation stucks when PGE failed

### ISSUE THREAD

**Issue by eazzzon** [ComputationalThermodynamics/MAGEMin#59]
Hi,

I am extracting the solidus of a self defined composition, the calculation gets stuck with high refinement (usually > 4), it seems usually happens when there are many PGE fails, then slows down the calculation and eventually stuck (not an error, just stays there), any idea how to solve this? I can email Nicolas the composition if needed.

Eason

**Comment by NicolasRiel** [comment]
Hi Eason,

Yes please forward me the composition. I will have a look. An update on the database will also arrive soon, I will also try if this fix your problem,

Cheers,

Nicolas

**Comment by NicolasRiel** [comment]
Which version of MAGEMin do you use btw? Is it the 1.3.1?

Nico

**Comment by eazzzon** [comment]
Hi Nico, just sent you an email about details. 

I am using 1.3.1 with a local compiled one but not the BinaryBuilder (local complied also as 1.3.1), somehow i can't switch to BinaryBuilder model. 

Maybe I should wait for the next version and see if it would fix? The legacy solver still works fine for me

**Comment by NicolasRiel** [comment]
Hi Eason,

MAGEMin 1.3.2 should arrive soon(ish) and will fix the problems of stalling calculations. Actually the version is ready, I am only  waiting for the green light from the TC team that developed the new thermodynamic models.

**Comment by NicolasRiel** [comment]
Hi Eason,

Does the last version 1.3.2 fixed your problems?

**Comment by eazzzon** [comment]
> Hi Eason,
> 
> Does the last version 1.3.2 fixed your problems?

Hi Nico,

A bit late, I just tested and the problems have been fixed! also the appearance of mysterious O phase is also fixed. Thanks a lot!

Eason

**Comment by NicolasRiel** [comment]
Awesome!

Please tell us if you meet any other issues.

Cheers
