### ISSUE TITLE
Documentation needs to be a bit better

### ISSUE THREAD

**Issue by k-a-mendoza** [ComputationalThermodynamics/MAGEMin#62]
In the julia interface, you send numbers like 0,1,2,3 to determine which bulk rock composition to use. Where do I go to see what these numbers refer to and their basic compositions?

**Comment by NicolasRiel** [comment]
Yes these number refer to predefined bulk-rock that serve as tests. We thought that most users would use custom bulk-rock compositions, which you can set following the doc provided here: https://computationalthermodynamics.github.io/MAGEMin/julia/Run.html#provide-custom-bulk-rock-composition.
That being said there is indeed no clear documentation on the pre-defined bulk rocks. I will correct that for version 1.3.3. For the time being you can access these information as comment in the main source code:
https://github.com/ComputationalThermodynamics/MAGEMin/blob/main/src/initialize.h line 668 and onward

Each database contain its set of test bulk rock for instance for metapelite the function is "get_bulk_metapelite"

Hope this helps,

**Comment by NicolasRiel** [comment]
The documentation has been updated to present the different predefined tests
