### ISSUE TITLE
Suppressing liquid 

### ISSUE THREAD

**Issue by AndreaRielli** [ComputationalThermodynamics/MAGEMin#65]
Hi! I have just started using MAGEMin and I was wondering wether it is possible to suppress liquid and obtain results for metastable assemblages (I have been looking for something to achieve this in the Matlab GUI but I couldn't find anything)
Thanks
Andrea

**Comment by NicolasRiel** [comment]
Hi Andrea,
This option is not implemented yet.  However, it is fairly straightforward to add it. I will see if I can add this feature in the upcoming week(s).
If you don't need to produce a phase diagram (if single point phase prediction is enough), this can be however achieved using the Julia interface. If you are interested I can help with that.

Nicolas

**Comment by NicolasRiel** [comment]
Hi Andrea, 
I added the option to suppress solution phases when using MAGEMin_C and MAGEMinApp.

I will add the documentation for MAGEMin_C, but in the test.jl you can see how it is done.

I close the issue!

Cheers
