### ISSUE TITLE
MAGEMin_App error

### ISSUE THREAD

**Issue by basalt78** [ComputationalThermodynamics/MAGEMin#76]
Howdy

I get the following error when trying to install MAGMin_App following the instructions

(@v1.10) pkg> add MAGEMinApp
ERROR: The following package names could not be resolved:
 * MAGEMinApp (not found in project, manifest or registry)

Can you please advise on how to resolve this?
Thanks,
Eric

**Comment by NicolasRiel** [comment]
Hi,

Yes the package is still in progressed of being registered. There is a 3 days quarantine for new packages that should end today.

Meanwhile you can always use the package by downloading the zip then open a terminal and place yourself at the root of the directory and activate it manually:

`julia> ] activate .`
`julia> using MAGEMinApp`
`julia> App()`

Nico

**Comment by boriskaus** [comment]
Even easier is:
```Julia
julia>]
pkg> add https://github.com/ComputationalThermodynamics/MAGEMinApp.jl
julia> using MAGEMinApp
julia> App()
```

**Comment by basalt78** [comment]
Many thanks for the prompt replies @NicolasRiel and @boriskaus. The suggestion of @boriskaus works like a charm.

Regards,
Eric

**Comment by boriskaus** [comment]
It was registered,  so now you can install it with:
```Julia
pkg> add MAGEMinApp
julia> using MAGEMinApp
julia> App()
```
