### ISSUE TITLE
Plans for database customization?

### ISSUE THREAD

**Issue by sc-dyer** [ComputationalThermodynamics/MAGEMin#90]
This project is a great step into modernizing thermodynamic modelling. I would love to be able to use this in my work but I need to be able to customize the databases used like in PERPLE_X and theriak-domino. Are there plans to add straightforward database customization options such as deactivating certain phases, end-members or solution models?

**Comment by NicolasRiel** [comment]
Hi, 
Actually yes and I started to work on this. However, this will be available only for the Julia interface MAGEMin_C and for the GUI MAGEMinApp as allowing these options directly with the C version (though command line arguments) would be rather unpleasant to develop.

Deactivating solution phases and pure phases will be available soon, but certainly not before EGU. Concerning deactivating the end-members of solution phases themselves that would be much more tricky to implement, but is it what you are looking for too?

Another development that would come soon(ish) will be to have the option to mix the solution from all TC database. But this is currently still work in progress .

Cheers

**Comment by sc-dyer** [comment]
That is great news! One case I can think of off the top of my head where deactivating specific end-members was needed is geikielite in the ilmenite solution model. I guess it would be more straightforward to just implement alternate solution models for common cases like that though.

**Comment by NicolasRiel** [comment]
I added the option to suppress solution phases in MAGEMin_C and MAGEMinApp. There is an example in test.jl for MAGEMin_C. I will update the documentation accordingly soon.
I will also add the option to suppress pure phases. 

That being said if you want to have reformulated phases you are welcome to prepare a pull request!

Hope this helps,

Nicolas

**Comment by sc-dyer** [comment]
Incredible, thank you!
