### ISSUE TITLE
Mistake in zirconium_saturation?

### ISSUE THREAD

**Issue by Iddingsite** [ComputationalThermodynamics/MAGEMin#96]
Hi,

I believe there is something fishy on the new function zirconium_saturation for the Watson et Harrison, 1983 and Boehnke et al., 2023 models. I think `M` is not calculated properly.

I have a benchmark coming from StatGeochem.jl for Boehmke et al., 2023, which I believe is correct, so we can compare the 2 implementations.

```
using MAGEMin_C
using MAGEMin_C: zirconium_saturation
using StatGeochemBase: nansum

function Boehnke_tzircM(SiO2::Number, TiO2::Number, Al2O3::Number, FeOT::Number, MnO::Number, MgO::Number, CaO::Number, Na2O::Number, K2O::Number, P2O5::Number)
    #Cations
    Na = Na2O/30.9895
    K = K2O/47.0827
    Ca = CaO/56.0774
    Al = Al2O3/50.9806
    Si = SiO2/60.0843
    Ti = TiO2/79.865
    Fe = FeOT/71.8444
    Mg = MgO/24.3050
    Mn = MnO/70.9374
    P = P2O5/70.9723
    # Normalize cation fractions
    normconst = nansum((Na, K, Ca, Al, Si, Ti, Fe, Mg, Mn, P))

    K, Na, Ca, Al, Si = (K, Na, Ca, Al, Si) ./ normconst


    M = (Na + K + 2*Ca)/(Al * Si)
    return M
end

function Boehnke_tzircZr(SiO2, TiO2, Al2O3, FeOT, MnO, MgO, CaO, Na2O, K2O, P2O5, T)
    M = Boehnke_tzircM(SiO2, TiO2, Al2O3, FeOT, MnO, MgO, CaO, Na2O, K2O, P2O5)

    # Boehnke, Watson, et al., 2013
    ZrSat = @. max(497644. /(exp(10108. /(T+273.15) -0.32 -1.16*M)), 0)
    return ZrSat
end

data = Initialize_MAGEMin("mp", verbose=true);
Xoxides = ["SiO2","TiO2","Al2O3", "FeO", "MnO", "MgO", "CaO","Na2O", "K2O", "H2O",]
composition = [67.67; 0.015; 13.69; 0.23; 0.01; 0.04; 0.19; 4.08; 4.81; 6]

P = 5.0  # in kbar
T = 800.0  # in °C

sys_in = "wt"

out     = single_point_minimization(P, T, data, X=composition, Xoxides=Xoxides, sys_in=sys_in)

# find index of H2O in oxides
H2O_idx = findfirst(isequal("H2O"), ox)

# set H2O to 0
out.bulk_M_wt[H2O_idx] = 0
out.bulk_M[H2O_idx] = 0

# renormalise the composition
out.bulk_M .= out.bulk_M ./ sum(out.bulk_M)
out.bulk_M_wt .= out.bulk_M_wt ./ sum(out.bulk_M_wt)

compo_melt = copy(out.bulk_M_wt)

SiO2 = compo_melt[1]
TiO2 = compo_melt[8]
Al2O3 = compo_melt[2]
FeOT = compo_melt[5]
MnO = compo_melt[10]
MgO = compo_melt[4]
CaO = compo_melt[3]
Na2O = compo_melt[7]
K2O = compo_melt[6]
P2O5 = 0

Zr_sat_1 = Boehnke_tzircZr(SiO2, TiO2, Al2O3, FeOT, MnO, MgO, CaO, Na2O, K2O, P2O5, 800)

Zr_sat_2 = zirconium_saturation(out; model="B")
 
@show Zr_sat_1, Zr_sat_2
```
which outputs `(Zr_sat_1, Zr_sat_2) = (251.215763613959, 396.6669649033065)`. Note that I put H2O to 0 because it is calculated anhydrous in this package so we can compare. 
I think the problem may come from here
https://github.com/ComputationalThermodynamics/MAGEMin/blob/0c96d794aa2db79c2f77167b5e17b469bda3bb5c/julia/Zircon_saturation.jl#L10
and here
https://github.com/ComputationalThermodynamics/MAGEMin/blob/0c96d794aa2db79c2f77167b5e17b469bda3bb5c/julia/Zircon_saturation.jl#L15
I don't think you should use `out.bulk_M_wt` but `out.bulk_M` as I don't see any conversion to moles in your code and I am not sure this `ratio_cation` is the good approach. But I don't have time to investigate further for now, so maybe I am wrong!

Cheers,

**Comment by NicolasRiel** [comment]
Thanks for reporting the issue.

I was not sure about mol vs wt%. If I remember correctly it was not obvious in the papers.

Will double check that!
